### ISSUE TITLE
Numerical blowup in the bump-on-tail instability run

### ISSUE THREAD

**Issue by ShyamSS-95** [QuazarTech/Bolt#10]
The commit tag to refer regarding this issue is `ef7ab9798e7ec3a4ae0078663cf9baf4dc7f2251`:

The initial conditions which were setup in the code were the same as mentioned on page 21 of  https://hal.inria.fr/hal-00363643/PDF/RR-6856.pdf, which were setup in `params.py` as:
```python
position_space = dict(N_x     = 128,
                      x_start = 0,
                      x_end   = 20*np.pi,

                      N_y     = 3,
                      y_start = 0,
                      y_end   = 1.0,

                      N_ghost = 3
                     )

perturbation = dict(
                    pert_real = 0.04, 
                    pert_imag = 0,
                    k_x       = 0.5,
                    k_y       = 0*np.pi,\
                   ) 
velocity_space = dict(N_vel_x   = 128,
                      vel_x_max = 9.0, 

                      N_vel_y   = 1, 
                      vel_y_max = 9.0,

                      N_vel_z   = 1, 
                      vel_z_max = 9.0
                     )
time = dict(
            final_time   = 100.0,
            dt           = 0.1
           )

EM_fields = dict(
                 charge_electron = -10,
                 charge_ion      = 10, 
                 solver          = 'electrostatic'
                )
```
Additionally, changes were made to the `f_initial` function from the `non_linear_solver.initialize` submodule:
```python
    n_p = 0.9/np.sqrt(2*np.pi)
    n_b = 0.2/np.sqrt(2*np.pi)

    args.f = rho *\
             (n_p * af.exp(-0.5*vel_x**2) + n_b * af.exp(-0.5*((vel_x - 4.5)/0.5)**2))
```
We find that the electric field and density blows up to infinity after a few time-steps(beyond t = 1). Presented below is the data obtained till then: 
![plot](https://user-images.githubusercontent.com/19583419/27586512-37d46fbe-5b5e-11e7-988a-7789e2908472.png)

One possible reason for this may be due to the distribution function taking negative values. To look into this matter, I printed the number of elements in the distribution function array which are negative as well as the most negative element in the array. This was the output obtained:
```
Computing for Time = 0.1
elements = 5823
min      = -1.6420871147188808e-11
Computing for Time = 0.2
elements = 10026
min      = -7.734490298484887e-09
Computing for Time = 0.3
elements = 12375
min      = -3.603181751241551e-08
Computing for Time = 0.4
elements = 17649
min      = -2.792009523696518e-07
Computing for Time = 0.5
elements = 21438
min      = -1.9643272231630472e-06
Computing for Time = 0.6
elements = 22734
min      = -3.1268601536718854e-06
Computing for Time = 0.7
elements = 23364
min      = -3.447008442103095e-06
Computing for Time = 0.8
elements = 24687
min      = -3.5021956117562424e-06
Computing for Time = 0.9
elements = 26091
min      = -3.0053335059403765e-06
Computing for Time = 1.0
elements = 28494
min      = -7.5621378678210665e-06
Computing for Time = 1.1
elements = 0
min      = inf
```

**Comment by mchandra** [comment]
Can you show a plot of min(rho(x)) vs t?

**Comment by ShyamSS-95** [comment]
![plot](https://user-images.githubusercontent.com/19583419/27623894-3ecff132-5bfc-11e7-824f-2ac289997c77.png)
![0](https://user-images.githubusercontent.com/19583419/27624816-f63ab3ae-5bff-11e7-8c6a-13ae7e3d62b5.png)
![2](https://user-images.githubusercontent.com/19583419/27624819-f7c23d14-5bff-11e7-9b77-731a0a485141.png)
![3](https://user-images.githubusercontent.com/19583419/27624824-fa234b84-5bff-11e7-80fa-d98a2b18b7a7.png)
![5](https://user-images.githubusercontent.com/19583419/27624828-fdde97a6-5bff-11e7-9d0a-04c3b08f9c7a.png)
![6](https://user-images.githubusercontent.com/19583419/27624831-ff85b04e-5bff-11e7-8a82-bbf91ca9638a.png)

**Comment by mchandra** [comment]
The colorbars seem to suppress the negative values, perhaps because of scale. It would be interesting to make a plot of where the negative values appear, i.e., to see what regions of phase space are stressing the algorithm. 

Extract and plot the negative values using:
```
negative_f                     = np.zeros(f.shape)
negative_f_indices             = np.where(f < 0)
negative_f[negative_f_indices] = 1

plt.contour(x, v, negative_f, 100, cmap='grey')
```

**Comment by ShyamSS-95** [comment]
![0](https://user-images.githubusercontent.com/19583419/27631883-b0a6dd00-5c17-11e7-8bb8-93c6015ada90.png)
![1](https://user-images.githubusercontent.com/19583419/27631888-b0adb60c-5c17-11e7-8f29-e118f5fea524.png)
![2](https://user-images.githubusercontent.com/19583419/27631887-b0ac5cd0-5c17-11e7-9af9-db1c6303b63f.png)
![3](https://user-images.githubusercontent.com/19583419/27631884-b0a7acc6-5c17-11e7-8ad3-5af809104447.png)
![4](https://user-images.githubusercontent.com/19583419/27631885-b0a7fe88-5c17-11e7-9bbe-d635e1ba6d2e.png)
![5](https://user-images.githubusercontent.com/19583419/27631886-b0a9941e-5c17-11e7-8ed9-4f72ba25ca75.png)

**Comment by ShyamSS-95** [comment]
I ran the case with `charge_electron=-1`. It was earlier set to `charge_electron=-10`. The blow-up to infinity is observed to be happening at a later time. I've made the plot until the point where the blow-up occurs:
![max_evolution](https://user-images.githubusercontent.com/19583419/27831578-e40b8daa-60e8-11e7-9659-2dbe8c4f336c.png)
The contour plot of the distribution function at the time-step where the blowup occurs shows:
![t 17 5](https://user-images.githubusercontent.com/19583419/27831725-85f2769c-60e9-11e7-8279-a00085bef324.png)
The contour plots for the distribution function for last two time-steps before this blow-up occurs shows:
![t 17 4](https://user-images.githubusercontent.com/19583419/27831868-1bb0d6a6-60ea-11e7-8205-4a441bc554f3.png)
![plot](https://user-images.githubusercontent.com/19583419/27831945-62047798-60ea-11e7-9297-f6b9efe7d256.png)
I'm not sure if the issue may be due to too large a time-step. I've fired a run with a much smaller time-step to be sure.

**Comment by mchandra** [comment]
This is with the log(f) implementation?

**Comment by ShyamSS-95** [comment]
Yes.

**Comment by ShyamSS-95** [comment]
I did the same run as above after implementing FFT interpolation in velocity space. It still blows up. But not till infinity. Also, at late times I observed that the distribution function goes much larger than one. These were the plots that were obtained:
![1](https://user-images.githubusercontent.com/19583419/27857635-19eeb134-6190-11e7-9580-bd8fa5c44637.png)
![2](https://user-images.githubusercontent.com/19583419/27857637-1a63663c-6190-11e7-888b-578d2c417c8c.png)
![3](https://user-images.githubusercontent.com/19583419/27857640-1c082e0a-6190-11e7-8fde-a6025f8f7eaa.png)

**Comment by mchandra** [comment]
1) Why all of a sudden FFT interpolation? It would make things worse because of GIbbs oscillations near discontinuities.
2) What is the output of the earlier run with a smaller time step?
3) Can you try a run with log(f) and with collisions? Choose tau ~ 10*dt.

**Comment by ShyamSS-95** [comment]
1. It was just something I was trying out
2. This is the result for `Nx = 128, Nvy = 128, dt = 0.001, t_final = 50`:
With `af.interp.CUBIC_SPLINE`, collisionless:
![plot](https://user-images.githubusercontent.com/19583419/27860874-15466a1c-619c-11e7-8c36-1f52aef69306.png)
With FFT interpolation, collisionless:
![fft_interpolation](https://user-images.githubusercontent.com/19583419/27860386-06be1564-619a-11e7-9ed0-4c4a4d99e895.png)
3. There's something wierd with the result for this. This is the plot for `tau = 0.01, af.interp.CUBIC_SPLINE, dt = 0.001, t_final = 5`:
![plot](https://user-images.githubusercontent.com/19583419/27861201-7010f538-619d-11e7-8cc1-625d05050695.png)
4. I was using `dt = 0.1` since another code also did so with the same parameters.(mentioned [here](https://hal.inria.fr/hal-00363643/PDF/RR-6856.pdf)). But now, I'm just ensuring that `dt<tau` and `vel_max * dt <dx`, and lowering `dt` when the simulation blows up.

**Comment by ShyamSS-95** [comment]
These are the results obtained when run with `Nx = 128, Nvx = 128, dt = 0.01, t_final = 200` for the collisionless case:
![linear](https://user-images.githubusercontent.com/19583419/27878690-b5f4b730-61dc-11e7-8778-7f7a2355f187.png)
![semilogy](https://user-images.githubusercontent.com/19583419/27878698-b98d1d2e-61dc-11e7-995d-14326ed57e62.png)
For comparison these are the results as presented in the reference [paper](http://aip.scitation.org/doi/abs/10.1063/1.862470):
![bumpontail](https://user-images.githubusercontent.com/19583419/27878793-0a4b6bb2-61dd-11e7-8431-2c3411d7dcf7.png)

[This](https://cocalc.com/projects/b472f9f9-0b3e-42ca-bcbf-5028649faa31/files/bump_on_tail_movies/Nx_128_Nv_128.mp4) is the movie of the evolution of the distribution function.

**Comment by ShyamSS-95** [comment]
I had initially misattributed the cause for the blow up due to the time-step size. However, that wasn't the cause for the blowup. The following results were obtained for the collisionless case with `t_final=200`:
- Using `dt = 0.1`:
![0 1](https://user-images.githubusercontent.com/19583419/27944593-98fc4c72-6305-11e7-96a5-5da84cbf69b8.png)
- Using `dt = 0.01`:
![semilogy](https://user-images.githubusercontent.com/19583419/27944631-def384f2-6305-11e7-9776-7b3ba64ff534.png)
- Using `dt = 0.001`:
![2017-07-05](https://user-images.githubusercontent.com/19583419/27944676-238c25c4-6306-11e7-821f-c34284971603.png)
The actual reason for the blowup was due to the interpolation scheme that was utilised in velocity space. Initially, I was using a 5th order spline interpolation using `scipy.InterpolatedUnivariateSpline`:
```python
  for i in range(vel_x.shape[0]):
    args.log_f[i, 0, :, 0] = af.to_array((InterpolatedUnivariateSpline(np.array(vel_x[i, 0, :, 0]), np.array(args.log_f[i, 0, :, 0]), k = 5))(np.array(vel_x_new[i, 0, :, 0])))
```
This was introduced when I was trying to check the influence of the order of the interpolation scheme on the order of convergence in the Landau damping case. When the interpolation scheme was reverted back to `af.INTERP.CUBIC_SPLINE`, the results produced were without numerical blowup:
```python
  args.log_f = af.approx1(af.reorder(args.log_f, 2, 3, 0, 1),\
                          af.reorder(vel_x_interpolant,2, 3, 0, 1),\
                          af.INTERP.CUBIC_SPLINE,\
                          off_grid = -46
                         )
  args.log_f = af.reorder(args.log_f, 2, 3, 0, 1)
```

**Comment by mchandra** [comment]
Ah! Can you now run the exact same setup but without the log(f) implementation? Lets see if log(f) actually improved the robustness of the scheme.

**Comment by ShyamSS-95** [comment]
This is the result when f is evolved (**NOT** log(f)). The run was performed for `dt = 0.1, t_final = 200, Nx = Nvx = 128` in the collisionless regime:
![plot](https://user-images.githubusercontent.com/19583419/27983971-ee964196-63e7-11e7-9d62-720db5bad9e2.png)

**Comment by mchandra** [comment]
1. What commit is this?
2. What is different from the setup in the first message of this issue (commit: ef7ab9798e7ec3a4ae0078663cf9baf4dc7f2251) and the latest simulation?

**Comment by ShyamSS-95** [comment]
1. Refer to commit [80d7f69](https://github.com/ShyamSS-95/Boltzmann_solver/tree/80d7f69c9090cfbccb4eb194545f8d04a2881cd4). This is the version of the log(f) implementation that was used in getting the above results. For the f evolution no separate commit was made since it just requires the change of primitive variable from log(f) to f.
2. The charge in the 1st message was taken as -10, while a charge of -1 has been taken in the results as given by the last 3 posts(posted by me). Additionally, as I've mentioned above the interpolation scheme was changed.

I've compared the results as given by the log(f) implementation and the f implementation:
![plot](https://user-images.githubusercontent.com/19583419/27984172-4dfe6092-63ec-11e7-9390-baddcea007c3.png)

**Comment by mchandra** [comment]
Ok good, looks like their evolution matches in the linear regime and is statistically similar in the non-linear regime.

1. Can you run the linear theory code with the same initial conditions and plot that as well?
2. Does it work with collisions?

**Comment by ShyamSS-95** [comment]
1.
![lt_vs_ck](https://user-images.githubusercontent.com/19583419/28003705-41f19496-655d-11e7-9a43-a16cd9a08a89.png)


2. I'll have to look into it. It's still blowing up.

**Comment by ShyamSS-95** [comment]
Issue is resolved. Works in #39
