### ISSUE TITLE
Use parallel HDF5 I/O

### ISSUE THREAD

**Issue by mchandra** [QuazarTech/Bolt#14]
Commit : dd269825853cc2131d1f3adfd1b4deb0b253d418

In `run_folder/run_non_linear_solver.py` the density is being written to disk by first gathering the data onto the rank 0 proc and then using h5py:
```
# Performing a reduce operation to obtain the global data:
comm.Reduce(data,\
            global_data,\
            op = MPI.MAX,\
            root = 0
           )

# Export of the global-data:
if(comm.rank == 0):
  import h5py
  h5f = h5py.File('ck_density_data.h5', 'w')
  h5f.create_dataset('density_amplitude', data = global_data - config.rho_background)
  h5f.create_dataset('time', data = time_array)
  h5f.close()

```

This needs to be replaced by `vecview()` in `petsc4py` which performs parallel HDF5 I/O (provided `petsc` is built with HDF5 support : `--download-hdf5=1`).

**Comment by ShyamSS-95** [comment]
There is no equivalent `vecview()` function in `petsc4py`. 
Additionally, the data is being gathered manually since it's searching for the global maximum of the density amplitude in the domain.

**Comment by mchandra** [comment]
Ah. I now see that the comment and the code are mismatched, and the variables names are un-informative:
```
# Performing a reduce operation to obtain the global data:
comm.Reduce(data,\
            global_data,\
            op = MPI.MAX,\
            root = 0
           )
```
1. The comment gives the reader the impression that you are gathering `data` from all the procs and putting them into `global_data`, but the code actually corresponds to picking out the max of `data` and putting them into `global_data`.
2. The variables names `data` and `global_data` are not giving any useful information. Examples of better choices are `density`, `density_peak`
3. Regarding equivalent of `vecview()`, you already seem to be using it to output the distribution function:
```
77  PETSc.Object.setName(global_vector, 'distribution_function')
78  viewer = PETSc.Viewer().createHDF5('ck_distribution_function.h5', 'w', comm = comm)
178 global_vec_value[:] = np.array(f_final[N_ghost:-N_ghost, N_ghost:-N_ghost, :])
179 viewer(global_vector)
```
Here again, the variables names `global_vector` and `global_vec_value` are not giving much information about the physical variable that they corresponds to. Also, use code in as local a scope as you can. The `viewer` object is being defined in lines 77-78, but is being used in lines 178-179 (commit: dd269825853cc2131d1f3adfd1b4deb0b253d418).

**Comment by ShyamSS-95** [comment]
Alright. I'll make the changes
Regarding `3)` - I was aware of that. Just wanted to point out that there is no direct equivalent for the function `vecview()`

**Comment by ShyamSS-95** [comment]
Functions for loading and dump of files exist in #39 

While `dump_distribution_function` and `dump_moments` is used to perform a HDF5 parallel output
Functions `load_distribution_function` is used to load from a file.
