### ISSUE TITLE
Deciding LICENCE

### ISSUE THREAD

**Issue by ShyamSS-95** [QuazarTech/Bolt#16]
Title self-explanatory.
GNU GPLv3 seems like the most suitable from my perspective.

**Comment by mchandra** [comment]
Lets go ahead with GNU GPLv3.

**Comment by mchandra** [comment]
1. Only route to master is through pull request. Do not commit directly.
2. When closing issues, mention the PR.
3. Open a PR for the licence. We need to put the copyright.

**Comment by ShyamSS-95** [comment]
Fixed in #20 #26
