### ISSUE TITLE
Name for the code

### ISSUE THREAD

**Issue by mchandra** [QuazarTech/Bolt#17]
Must be cool.

Rejected list:
1. SLaPy

**Comment by ShyamSS-95** [comment]
Question: Does the name have to be an acronym?

**Comment by mchandra** [comment]
No need. You got any ideas?

**Comment by ShyamSS-95** [comment]
What do you think of the following:
- Inferno
- Tesseract
- Artemis
- Fury
- Avalanche

**Comment by mchandra** [comment]
:O 

How about: "Bolt: A (Fast?) Semi-Lagrangian Solver for Kinetic Theories" ?

**Comment by ShyamSS-95** [comment]
Yeah. I like it as well. That'll work

**Comment by ShyamSS-95** [comment]
Issue was fixed in #20 #26
