### ISSUE TITLE
Linear solver does not solve electrostatic system

### ISSUE THREAD

**Issue by mchandra** [QuazarTech/Bolt#18]
Commit: c08646c6597692897268756d5c16455eb812470b

The linear solver solves the full set of dynamical  Maxwells equations even when `EM_fields['solver'] = "electrostatic"` in `params.py`. Here is the relevant code from the function `dY_dt()` in `linear_solver/evolve.py`:

```
  ddelta_E_x_hat_dt = (delta_B_z_hat * 1j * k_y) - delta_J_x_hat
  ddelta_E_y_hat_dt = (- delta_B_z_hat * 1j * k_x) - delta_J_y_hat
  ddelta_E_z_hat_dt = (delta_B_y_hat * 1j * k_x - delta_B_x_hat * 1j * k_y) - delta_J_z_hat

  ddelta_B_x_hat_dt = (- delta_E_z_hat * 1j * k_y)
  ddelta_B_y_hat_dt = (delta_E_z_hat * 1j * k_x)
  ddelta_B_z_hat_dt = (delta_E_x_hat * 1j * k_y - delta_E_y_hat * 1j * k_x)

  fields_term = (charge_electron / mass_particle) * (delta_E_x_hat + \
                                                     delta_B_z_hat * vel_y - \
                                                     delta_B_y_hat * vel_z
                                                    ) * dfdv_x_background  + \
                (charge_electron / mass_particle) * (delta_E_y_hat + \
                                                     delta_B_x_hat * vel_z - \
                                                     delta_B_z_hat * vel_x
                                                    ) * dfdv_y_background  + \
                (charge_electron / mass_particle) * (delta_E_z_hat + \
                                                     delta_B_y_hat * vel_x -\
                                                     delta_B_x_hat * vel_y
                                                    ) * dfdv_z_background

```

In the electrostatic mode, the EM fields are no longer dynamical variables that are evolved using `dY_dt` and should instead be solved for using `compute_electrostatic_fields`. In particular, `dY_dt` should not return `ddelta_E_x_hat_dt` etc and `delta_E_x_hat` etc needed to evaluate the `fields_term' need to be computed using `compute_electrostatic_fields` inside the function.

Note that this bug does not affect 2D2V results when `B_z = 0` since any non-zero `(B_x, B_y)` are only multiplied by `vel_z` in `fields_term` shown above, and  `vel_z=0` for the 2V mode.

**Comment by ShyamSS-95** [comment]
Fixed in #20 #26
