### ISSUE TITLE
What does additional_terms() in advection_terms.py do?

### ISSUE THREAD

**Issue by mchandra** [QuazarTech/Bolt#29]
#### Question: 
This segment of the code in `src/nonrelativistic_boltzmann/advection_terms.py` is not clear to me:

```
class _additional_terms(object):
    def __init__(self):
        return

    def T1(self, q1, q2):
        return (q1 * q2)
```

What exactly does the above correspond to mathematically and how is it used in the following:

```
def A_p(q1, q2, p1, p2, p3,
        E1, E2, E3, B1, B2, B3,
        params,
        additional_terms=None):
    """Return the terms A_p1, A_p2 and A_p3."""
    # Additional force terms can be passed through additional_terms:
    F1 = (params.charge_electron / params.mass_particle) * (E1 +
            p2 * B3 - p3 * B2)
    F2 = (params.charge_electron / params.mass_particle) * (E2 -
            p1 * B3 + p3 * B1)
    F3 = (params.charge_electron / params.mass_particle) * (E3 -
            p2 * B1 + p1 * B2)

    return (F1, F2, F3)
```

Thanks

**Comment by ShyamSS-95** [comment]
It's not being used in the nonrelativistic-Boltzmann case. That definition is just there to show that if a model is to be defined in which  `A_p1, A_p2, A_p3`  contain terms other than the EM field quantities, they can be passed through the `additional_terms` object.

**Comment by ShyamSS-95** [comment]
@mchandra 
That was something I was considering at the time of designing the framework if we need to pass terms for the advection terms in p-space which contain terms apart from the EM-fields. I'll remove it now, since additional terms can be written directly, or by making use of functions:

```python
def T1(q1, q2, p1, p2, p3):
    return (q1 * q2/(p1*p2*p3))
    
def T2(q1, q2, p1, p2, p3):
    return(p1*p2*p3/(q1*q2))

def A_p(q1, q2, p1, p2, p3,
        E1, E2, E3, B1, B2, B3,
        params
        ):
    F1 =   (params.charge_electron / params.mass_particle) 
         * (E1 +p2 * B3 - p3 * B2) + T1(q1, q2, p1, p2, p3)
    F2 =   (params.charge_electron / params.mass_particle) 
         * (E2 - p1 * B3 + p3 * B1) + T2(q1, q2, p1, p2, p3)
    F3 =   (params.charge_electron / params.mass_particle) 
         * (E3 - p2 * B1 + p1 * B2)

    return (F1, F2, F3)
```
In the above example case, I'm assuming in my model, the advection terms `A_p1, A_p2` contain the terms T1 and T2 in addition to the EM fields terms.

**Comment by mchandra** [comment]
Ok, the second method is much more transparent to me. Does PR #27 have this?

**Comment by ShyamSS-95** [comment]
Yes. Now. It does. I just pushed a commit. Refer to 1440e717f91060e5e739c67b2e08f0a43dc4b319
