### ISSUE TITLE
Issue with accuracy in LT

### ISSUE THREAD

**Issue by ShyamSS-95** [QuazarTech/Bolt#8]
The LT code seems to require a high order of time integration to maintain accuracy. Currently, a 6th order time-stepping is implemented in #7 to get correct results in the convergence tests .This dependence on the time-integration order seems to become more crucial when dealing with higher dimensional data structures. This needs to be looked into.

**Comment by ShyamSS-95** [comment]
The issue was fixed in [80d7f69](https://github.com/ShyamSS-95/Boltzmann_solver/commit/80d7f69c9090cfbccb4eb194545f8d04a2881cd4) on branch 'log_f_implementation' of my fork. The issue was due to a mistake in the RK-4 timestepper's implementation. The same will be updated when merging with master.

**Comment by mchandra** [comment]
That's great. Please close this issue only after a pull request and by explicitly mentioning which PR fixes the issue.

**Comment by mchandra** [comment]
Issue was fixed in PR #20 #26
