### ISSUE TITLE
Performance Issues

### ISSUE THREAD

**Issue by ShyamSS-95** [QuazarTech/Bolt#9]
There seems to be an issue with the performance of the code. We've found that a major cause of the slowdown seems to be due to the communication routines. For the resolution of (Nx, Ny, Nvx, Nvy, Nvz) = (32, 32, 32, 32, 32), when run on 4 TeslaK80 GPU's, a single time-step takes 4.5 seconds ~ 227.5 spatial zone-cycles per second.

However with the communication routines commented out, the same run takes 0.46s per time-step ~ 2226.086 spatial zone-cycles per second

**Comment by mchandra** [comment]
Being worked upon in #24
